name: Build AAB
on: [push]
jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install
        run: |
          sudo apt update
          sudo apt install -y zip unzip openjdk-17-jdk
          pip install buildozer cython==0.29.33
      - name: Create spec
        run: |
          echo "[app]
          title = SENTINEL
          package.name = sentinel
          package.domain = com.ahmad.sentinel
          source.dir =.
          version = 1.0
          requirements = python3,kivy==2.3.0,opencv,numpy,pillow
          orientation = portrait
          android.api = 33
          android.minapi = 24
          android.ndk = 25b
          android.accept_sdk_license_agreements = True
          android.release_artifact = aab
          [buildozer]
          log_level = 2" > buildozer.spec
      - name: Build
        run: buildozer android release
      - name: Upload AAB
        uses: actions/upload-artifact@v4
        with:
          name: SENTINEL-AAB
          path: bin/*.aab
